<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "contentimporter"
 *
 * Auto generated by Extension Builder 2017-01-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Content Importer',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Susanne Moog',
    'author_email' => 'susanne.moog@typo3.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
